server:
  port: 8082

spring:
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  application:
    name: restaurant-statistics

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
