spring:
  application:
    name: restaurant-system
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
