server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D_disk/restaurant-system/backend/Config-server/src/main/resources/config
